# Generated by Django 5.2 on 2025-04-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionlog",
            name="computer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sessionlog",
            name="session_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
